### ISSUE TITLE
Diamond helmet recipe broken in 1.16.3

### ISSUE THREAD

**Issue by nurdism** [Caltinor/DiceMC-Tiered-Armors#1]
![example](https://i.imgur.com/yN2J58D.png)

~~this might be due to src/main/resources/data/dicemcta/recipes/diamond_helmet.json L15 `minecraft:iron_ingot` being defined but not used?~~ Can confirm, it was indeed  https://github.com/Caltinor/DiceMC-Tiered-Armors/blob/master/src/main/resources/data/dicemcta/recipes/diamond_helmet.json#L15

**Comment by Caltinor** [comment]
Resolved with Commit#e0d50ef 
New version pushed to CF.
